# Generated by Django 4.2.17 on 2026-03-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='estimated_minutes_per_order',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
