# Generated by Django 4.2.17 on 2026-03-27 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_menucategory_remove_restaurant_version_nonnull'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['sort_order']},
        ),
    ]
