# Generated by Django 4.2.17 on 2026-05-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0021_accepting_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantstaff',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='restaurantstaff',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], max_length=10),
        ),
    ]
