# Generated by Django 5.2.14 on 2026-05-17 23:31

from django.db import migrations


def rename_roles(apps, schema_editor):
    RestaurantStaff = apps.get_model("restaurants", "RestaurantStaff")
    RestaurantStaff.objects.filter(role="manager").update(role="admin")
    RestaurantStaff.objects.filter(role="kitchen").update(role="member")


def reverse_rename(apps, schema_editor):
    RestaurantStaff = apps.get_model("restaurants", "RestaurantStaff")
    RestaurantStaff.objects.filter(role="admin").update(role="manager")
    RestaurantStaff.objects.filter(role="member").update(role="kitchen")


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0022_restaurantstaff_permissions_and_more'),
    ]

    operations = [
        migrations.RunPython(rename_roles, reverse_rename),
    ]
