# Generated by Django 4.2.17 on 2026-02-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="parsed_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
