# Generated by Django 4.2.17 on 2026-03-27 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_external_order_id_order_pos_sync_status_and_more'),
        ('orders', '0004_backfill_confirmed_at'),
    ]

    operations = [
    ]
